spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 40711195195-c7ep5ckqivp26qrvm4nrmncinmtl71ni.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
              
          kakao:    
            client-id: ec7060654782b16e343442ddfbddb9c6
            client-secret: 8m6pjQwCHTZoF8Qb2WMCOmMguEPE9wPR
            redirect-uri: http://localhost:9000/login/oauth2/code/kakao
            authorization-grant-type : authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
             - profile_nickname
             - account_email
             
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id	
             
        